### PR TITLE
feat(version): enable master branch name to be configured

### PR DESCRIPTION
**Pull request by hass123uk**
Allow the user to define the name of their main/release branch.

*Issue #, if available:*
#146

*Description of changes:*
* Add new common node option that defines default release branch. 
  * Use this for the default value of the release branches.
  * Use for the value of the branch where version tags are pushed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by eladb — COMMENTED** [review]
I think the GitHub workflows also reference 'master'. No?

**Comment by hass123uk** [comment]
> I think the GitHub workflows also reference 'master'. No?

Yes, it takes in an array of release branches that default to [ 'master' ].
If we reuse this, would you, on release, push the code & tags to all branches within this array.

**Comment by eladb** [comment]
> If we reuse this, would you, on release, push the code & tags to all branches within this array.

I think the other way around. I would expect the default value for `releaseBranches` to be aligned with the newly introduced `releaseBranch` so it works out of the box if I change the release branch to something that's not `master`.

**Comment by hass123uk** [comment]
Perhaps the option should be called main-branch instead.

**Review by eladb — APPROVED** [review]

**Pull request merged**
